### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by grhabyt** [adafruit/adafruit-arduino-proxy#1]
OS X 10.10.2, Arduino 1.63, Node 0.12.2
I can't get Adafruit boards to show in Board Manager.
Could you detail what is supposed to happen after I run node proxy.js ? I get no response in Terminal. Is that correct?

**Comment by toddtreece** [comment]
@grhabyt if you are just looking to test it out with Adafruit boards, you can set the proxy settings to this in your Arduino v1.6.3 IDE preferences:

HTTP Server: `apt.adafruit.com`
HTTP Port: `5050`
