### ISSUE TITLE
Support for third-party boards

### ISSUE THREAD

**Issue by Arachnid** [adafruit/adafruit-arduino-proxy#2]
Do you have any interest in accepting pull requests to add other third-party boards to your repository? What you've done here is fantastic, and it will work even better if there's a single repository people can point their IDEs to for a wide variety of 3rd party Arduino-based boards; expecting users to change the proxy address for each new board they install obviously isn't too practical. It'd be great if Adafruit were the ones maintaining a repository of open-source Arduino board files.

Alternately, if you're not interested, would you be amenable to contributing your own boards to an impartial third-party repository of board files?

**Comment by toddtreece** [comment]
@Arachnid sorry, i missed this. apparently i changed a setting at some point and github stopped auto-watching new repos for my user.

third party boards are now officially supported, and you can check out this tutorial for help with adding to v1.6.4: https://learn.adafruit.com/add-boards-arduino-v164
