### ISSUE TITLE
Can´t make it work

### ISSUE THREAD

**Issue by brunocannavina** [adafruit/adafruit-arduino-proxy#3]
I add apt.adafruit.com as the Server (HTTP) under Proxy Settings with a Port (HTTP) of 5050 
but when I click on boards manager nothing changes..
I don´t have antivirus and I 'm running arduino 1.6.3 on windows.
Can anyone help me?

**Comment by toddtreece** [comment]
@brunocannavina sorry, i missed this. apparently i changed a setting at some point and github stopped auto-watching new repos for my user.

third party boards are now officially supported, and you can check out this tutorial for help with adding to v1.6.4: https://learn.adafruit.com/add-boards-arduino-v164
